fin servlet
roroross/step pull request #4
Opened 2020-12-16 22:28 UTC by roroross

finished servlet step of tute

2020-12-17 03:31 UTC, sbland-g requested changes

2020-12-17 03:31 UTC, sbland-g commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    //same font and size
Pick one; leave the other out. It's generally considered bad practice to leave in commented out code.

2020-12-17 03:49 UTC, Techget commented on walkthroughs/week-3-server/examples/page-view-counter/src/main/java/com/google/sps/servlets/PageViewServlet.java
> +  //do get function below runs whenever a client sends a GET request to the servlet URL
These 2 sentences are a bit duplicated

2020-12-17 03:49 UTC, Techget commented on walkthroughs/week-3-server/examples/page-view-counter/src/main/java/com/google/sps/servlets/PageViewServlet.java
> +    /*
You many want to remove this comment? As the following snippet is quite similar.

2020-12-17 03:49 UTC, Techget commented on walkthroughs/week-3-server/examples/page-view-counter/src/main/webapp/index.html
> +    <!-- <p>Click <a href="/content">here</a> to view afkdjfka;jdkjajfadjfa; generated by a servlet.</p> -->
Similiar as above, do you need the comment?

2020-12-19 15:01 UTC, roroross reviewed
reflected comments and feedback in latest git push

2020-12-19 15:01 UTC, closed without merging